version: '2'
services:
    jhdemo-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhdemo/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhdemo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
